#!/usr/bin/env bash
#
# ytw - wrapper for youtube
# dependencies: mpv, rofi, youtube-dl, python, ttf-nerd-fonts-symbols, xclip, libnotify
# github.com/yrwq

YTW_PATH=$HOME/.local/share/ytw

# path of the downloaded cover image
cover_path=$YTW_PATH/ytw_cover.jpg

# path to download music files
# music_dir=$HOME/Music
music_dir=$HOME/etc/music
vid_dir=$HOME/etc/vid

# launch rofi with these arguments
rofi_args="-dmenu -i -matching fuzzy -p "

# which menu/launcher to use
# menu="dmenu -i -l 15"
menu="rofi $rofi_args"

# playlist file, used when -l argument passed
# in the file you should seperate the url with a tab
# example:
# title		url

vidlist="/home/$USER/.config/playlist"
# vidlist="$YTW_PATH/playlist"

# audio download args
ytdl_args="--add-metadata --embed-thumbnail \
	--extract-audio --audio-format mp3 --audio-quality 0 --prefer-ffmpeg \
	--ignore-errors --restrict-filenames --verbose -o $music_dir/%(title)s.%(ext)s"

# help message
usage(){
cat << EOF

Usage:
	ytw -l		pick from a playlist
	ytw -s		search on youtube
	ytw -d 		download audio
	ytw -v 		download video
	ytw <url>	download url as audio

EOF
}

# main menu
main(){
	choices=" Search\n Playlist\n陼 Edit playlist"
	choice=$(echo -ne ${choices} | $menu)
	fin=$(echo ${choice} | awk '{print $2}')
	case $fin in
		"Search")
			search
		;;
		"Playlist")
			playlist
		;;
		"Edit playlist")
			$TERMINAL -e $EDITOR $vidlist
		;;
	esac
}

generate(){
	# search on youtube with rofi
	sh $YTW_PATH/utils -s

	# generate values
	sh $YTW_PATH/utils -m

	# prompt the user to choose from generated values
	choice=$(cat $YTW_PATH/choices | $menu)

	# exit if choice doesn't exist
	[[ -z "$choice" ]] && { exit 1; }

	# get information about video
	id=$(echo -e ${choice} | awk '{print $1}' )
	infos=$(cat $YTW_PATH/values)
	thumbnail=$(echo $infos | jq .videos[$id].thumbnails | sed 's/[][]//g' | sed 's/"//g' )
	dur=$(echo $infos | jq .videos[$id].duration | sed 's/"//g')
	channel=$(echo $infos | jq .videos[$id].channel | sed 's/"//g')
	title=$(echo $infos | jq .videos[$id].title | sed 's/"//g')
	views=$(echo $infos | jq .videos[$id].views | sed 's/"//g')
	url=$(echo $infos | jq .videos[$id].url_suffix | sed 's/"//g')

	# download thumbnail for notifications
	curl -Ss $thumbnail -o $YTW_PATH/ytw_cover.jpg

}

search(){
	generate

	select="\n Play\n陼 Add to playlist\n螺 Add and play\n Download audio\n Download video\n"

	selmen=$(echo -ne "Title:${title} \nChannel:${channel}\nViews:${views}\nDuration:${dur}\n${select}" | $menu)
	fin=$(echo ${selmen} | awk '{print $2}')

	[[ -z "$select" ]] && { exit 1; }

	case $fin in
		"Play")
			# search on youtube
			link=https://www.youtube.com"$url"

			# copy link to clipboard
			echo $link | xclip -sel clip
			notify-send -i $cover_path "  Now playing" "${title}"
			# play the final link in mpv
  			mpv "$link"
		;;
		"Download audio")
			notify-send -i $cover_path " 	Downloading" ${title}
			link=https://www.youtube.com"$url"
			echo $link | xclip -sel clip
			youtube-dl $ytdl_args $link
		;;
		"Download video")
			notify-send -i $cover_path " Downloading" ${title}
			link=https://www.youtube.com"$url"
			echo $link | xclip -sel clip
			youtube-dl -f best -o "$vid_dir/%(title)s.%(ext)s" $link
		;;
		"Add to playlist")
			link=https://www.youtube.com"$url"

			echo -ne $title'	'$link'\n' >> $vidlist
			echo $link | xclip -sel clip
			notify-send -i $cover_path "陼Added" "${title}"
		;;
		"Add and play")
			link=https://www.youtube.com"$url"
			echo -ne $title'	'$link'\n' >> $vidlist
			notify-send -i $cover_path "陼Added & playing" "${title}"
			echo $link | xclip -sel clip
			mpv $link
		;;
	esac
}

playlist(){
	cat "$vidlist" | grep -P "^$(cat "$vidlist" | grep "https:" | sed 's/\t.*//g' | $menu | awk '{print $1}')\s" | sed 's/.*\t//' | xargs -r mpv
}

# handle urls
case $1 in

	# download as audio
	*youtube.com* | *youtu.be* | *soundcloud.com*)
		youtube-dl $ytdl_args $1
	;;

esac

if [ -z "$1" ]; then
	main
fi

# arguments
while getopts 'lsdvhf' flag; do
	case "${flag}" in
		l)
			playlist
			;;
		s)
			search
			;;
		f)
			generate
			;;
		h)
			usage
			;;
	esac
done
