#!/usr/bin/env bash
#
# ytw - wrapper for youtube
# dependencies: mpv, rofi, youtube-dl, python, sed, awk

YTW_PATH=$HOME/.local/share/ytw

# default settings
list=false
search=false
dl=false
video=false
audio=false

# launch rofi with theese arguments
rofi_args="-dmenu -p YouTube"

# which menu/launcher to use
# menu="dmenu -i -l 15"
menu="rofi $rofi_args"

# playlist file, used when -l argument passed
# in the file you should seperate the url with a tab
# example:
# title		url

# vidlist="/home/$USER/.config/playlist"
vidlist="$YTW_PATH/playlist"

# audio download args
ytdl_args="--add-metadata --embed-thumbnail \
	--extract-audio --audio-format mp3 --audio-quality 0 --prefer-ffmpeg \
	--ignore-errors --restrict-filenames --verbose"

# help message
usage(){
cat << EOF

Usage:
	ytw -l		pick from a playlist
	ytw -s		search on youtube
	ytw -d 		download audio
	ytw -v 		download video
	ytw <url>	download url as audio

EOF
}

# arguments
while getopts 'lsdvh' flag; do
	case "${flag}" in
		l)
			list='true'
			search='false'
			dl='false'
			audio='false'
			video='false'
			;;
		s)
			list='false'
			search='true'
			dl='false'
			audio='false'
			video='false'
			;;
		d)
			list='false'
			search='false'
			dl='true'
			audio='true'
			video='false'
			;;
		v)
			list='false'
			search='false'
			dl='true'
			audio='false'
			video='true'
			;;
		h)
			usage
			;;
	esac
done

choices="Search\nPlaylist\nAudio\nVideo\n
"

main(){
	choice=$(echo -ne ${choices} | $menu)
	case ${choice,,} in
		search)
			ytw -s
		;;
		playlist)
			ytw -l
		;;
		audio)
			ytw -d
		;;
		video)
			ytw -v
		;;
	esac
}

# search with rofi and play with mpv
# -s
if [ $search = 'true' ]; then
	# generate the json file
	sh $YTW_PATH/generate

	# clean up json, only pipe actual titles to menu
	choice=$(sh $YTW_PATH/getlist | $menu)

	# search on youtube
	yid=$(youtube-dl ytsearch:"$choice" -s | grep "\[youtube\]" | cut -d ']' -f 2 | awk -F ':' '{print $1}' | cut -c 2-)
	link=https://www.youtube.com/watch\?v\="$yid"

	# play the final link in mpv
  	mpv "$link"
fi

# playlist
# -p
if [ $list = 'true' ]; then
	# stole this from Luke Smith @lukesmithxyz
	if [ -z "$2" ]; then
		cat "$vidlist" | grep -P "^$(cat "$vidlist" | grep "https:" | sed 's/\t.*//g' | $menu | awk '{print $1}')\s" | sed 's/.*\t//' | xargs -r mpv
	fi

	if [ -n "$2" ]; then
		cat "$2" | grep -P "^$(cat "$2" | grep "https:" | sed 's/\t.*//g' | $menu | awk '{print $1}')\s" | sed 's/.*\t//' | xargs -r mpv
	fi
fi

# download audio
# -d
if [ $dl = 'true' ]; then
	# generate the json file
	sh $YTW_PATH/generate

	# clean up json, only pipe actual titles to menu
	choice=$(sh $YTW_PATH/getlist | $menu)

	# search on youtube
	yid=$(youtube-dl ytsearch:"$choice" -s | grep "\[youtube\]" | cut -d ']' -f 2 | awk -F ':' '{print $1}' | cut -c 2-)
	link=https://www.youtube.com/watch\?v\="$yid"

	if [ $audio = 'true' ]; then
		youtube-dl $ytdl_args $link
	elif [ $video = 'true' ]; then
		youtube-dl $link -f best
	fi
fi


# if argument is an url, download it as an audio
case $1 in

	*youtube.com* | *youtu.be* | *soundcloud.com*)
		youtube-dl $ytdl_args $1
	;;

esac


# if launched without arguments, show help message
if [ -z "$1" ]; then
	main
fi
