#!/bin/sh

YTW_PATH=$HOME/.local/share/ytw

# prompt the user for a video title
search="$(rofi -dmenu -p Youtube)"

# put the title between '
search="'$search'"

# if values.json exists, then remove
[ -e $YTW_PATH/values.json ] && rm $YTW_PATH/values.json

# generate json values
python $YTW_PATH/search.py -t "$search" > $YTW_PATH/values.json
