#!/usr/bin/env bash

values=$HOME/.local/share/ytw/values

duration(){
	for i in {1..10}
	do
		dur=$(cat $values | jq .videos[$i].duration | sed 's/"//g')
		echo $dur
	done
}

list(){
	for i in {1..10}
	do
		list=$(cat $values | jq .videos[$i].title | sed 's/"//g')
		echo $list
	done
}

case $1 in
	# get the whole title
	-t) cat $values | jq '.videos[].title' | sed 's/"//g' | sed 's/^/  /' ;;
	# cleaner version XD
	-c) cat $values | jq '.videos[].title' | sed 's/"//g' | sed 's/Official//Ig' | sed 's/Music//Ig' | sed 's/Video//Ig' | sed 's/(//g' | sed 's/)//g' | sed 's/Visualizer//Ig' | sed 's/  //g' | sed 's/HD//Ig' | sed 's/^/ /' ;;
	# get thumbnails
	-i) cat $values | jq '.videos[].thumbnails[]' | sed 's/"//g' ;;
	-d)
		duration
		;;
	-l)
		list
		;;
esac

main(){
	for i in {1..10}
	do
		dur=$(cat $values | jq .videos[$i].duration | sed 's/"//g')
		list=$(cat $values | jq .videos[$i].title | sed 's/"//g')
		echo $dur $list
	done

}

main
