#!/usr/bin/env bash

values=$HOME/.local/share/ytw/values
YTW_PATH=$HOME/.local/share/ytw

search(){
	# prompt the user for a video title
	search="$(rofi -dmenu -i -p )"

	# put the title between '
	search="'$search'"

	# if values.json exists, then remove
	[ -e $values ] && rm -rf $YTW_PATH/values

	# generate json values
	python $YTW_PATH/search.py -t "$search" > $YTW_PATH/values
}

duration(){
	for i in {1..10}
	do
		dur=$(cat $values | jq .videos[$i].duration | sed 's/"//g')
		echo $dur
	done
}

list(){
	for i in {1..10}
	do
		list=$(cat $values | jq .videos[$i].title | sed 's/"//g')
		echo $list
	done
}

thumbnails(){
	for i in {1..10}
	do
		thumbs=$(cat $values | jq .videos[$i].thumbnails | sed 's/"//g' )
		echo $thumbs
	done
}

case $1 in
	# get the whole title
	-t)
		thumbnails
		;;
	-d)
		duration
		;;
	-l)
		list
		;;
	-s)
		search
		;;
esac

for i in {0..9}
do
	# duration of the video in min:sec
	dur=$(cat $values | jq .videos[$i].duration | sed 's/"//g')

	list=$(cat $values | jq .videos[$i].title | sed 's/"//g')

	echo -e '  '$dur'    '$list | sed 's/^/ /'
done
